language: c++

compiler:
- clang
- gcc

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libboost-dev libcppunit-dev

# before build script, run autoreconf
before_script: ./autogen.sh
script: ./configure --disable-shared && make && make check
